artifacts_root: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: D:/PROJECTS/Dataset/Dataset.zip
  local_data_file: artifacts/data_ingestion/Dataset.zip
  unzip_dir: artifacts/data_ingestion
